<%@ Page Title="" Language="C#" MasterPageFile="~/Layout.master" AutoEventWireup="true" CodeBehind="MediaPage.aspx.cs" Inherits="FakeNews2019.Pages.MediaPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Content" runat="server">
    <dx:ASPxImageSlider ID="ASPxImageSlider1" runat="server" ImageSourceFolder="~/Content/Images/Initiative/">
        <SettingsAutoGeneratedImages ImageCacheFolder="~/Thumb/" />
        <Items>
            <dx:ImageSliderItem ImageUrl="~/Content/Images/Initiative/sahahkhabark.jpg">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/Content/Images/Initiative/norumors.jpg">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/Content/Images/Initiative/LierLogo arb.png">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/Content/Images/Initiative/fatabyyano.jpg">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/Content/Images/Initiative/Fadeh1.jpg">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/Content/Images/Initiative/check.pal.png">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/Content/Images/Initiative/akeed.jordan.jpg">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/Content/Images/Initiative/DaBegad.jpg">
            </dx:ImageSliderItem>
            <dx:ImageSliderItem ImageUrl="~/Content/Images/Initiative/Tech4Peace.png">
            </dx:ImageSliderItem>
        </Items>
    </dx:ASPxImageSlider>
</asp:Content>
